### ISSUE TITLE
Problem with basic Auth + Bitbucket

### ISSUE THREAD

**Issue by iJos** [DALTCORE/laravel-deploy-helper#6]
Hi 

I'm using a private repo on Bitbucket. 
The config is set like: "http://user:pass@git.server/repo.git"

But I'm receiving the next error: 
`fatal: unable to access 'https://username:passwordbitbucket.org/rest/of-the-repo-url.`
Note that username:password**bitbucket.org** is together.

I have some symbols in the password, the last one symbol is next to the @ symbol of the URL. I think that something is clearing the symbols to extract username and password but is failing because is not expecting symbols.

I you don't understand well the problem, I can provide more info.

Thanks in advance.

**Comment by RamonSmit** [comment]
Hi! 

It's probably a symbol in the password. For that method, you can't use **:** and **@** in the passwords,
What symbols are you using? I might can try to reproduce the problem. 

-- Ramon

*Edit*
I'm still looking for a way how I can use a public key for deployments, so we don't have to use passwords anymore. Any suggestion is welcome tho ;-)

**Comment by rpsimao** [comment]
I have the same issue with the password, my solution was to use a "\\" (backslash) before the password symbols.

Ex: https://rpsimao:\$1234\&1234@xxx.github.com

**Comment by RamonSmit** [comment]
Hmm! Valid one. I'm going to look how I can programatticly fix this :-) suggestions are welcome

```
'git clone -b ' . $branch . ' ' . config('laravel-deploy-helper.stages.' . $stage . '.git.http') . ' .',
```

It's set in here, can't i just set: addslashes?

**Comment by rpsimao** [comment]
addslashes() does not worked for me.

**Comment by RamonSmit** [comment]
I'm getting this from escapeshellcmd:
>>> echo escapeshellcmd('https://rpsimao:$1234&1234@xxx.github.com');
https://rpsimao:^$1234^&1234@xxx.github.com⏎

Can you test that around the config function?

Edit:

Tried locally, did not work ether :-\

**Comment by RamonSmit** [comment]
```
>>> echo escapeshellarg('https://rpsimao:\$1234\&1234@xxx.github.com');
"https://rpsimao:\$1234\&1234@xxx.github.com"⏎
```
Would you mind to test with ```escapeshellarg```

**Comment by rpsimao** [comment]
escapeshellarg(), does not work also.
I've tried with addcslashes('https://rpsimao:$1234&1234@xxx.github.com', '$&') with no luck

**Comment by RamonSmit** [comment]
Hmm, This is getting weird. 
I understand that the TTY of the server thinks you want to do some magic stuff with: $ and &, but there must be a way to escape this...

**Comment by rpsimao** [comment]
Yes if tested alone addcslashes('https://rpsimao:$1234&1234@xxx.github.com', '$&'), the $ and & are escaped.......

**Comment by RamonSmit** [comment]
Alright, If that works, we need to get a list with all possible characters that we need to escape I guess

**Comment by rpsimao** [comment]
```
 $git = addcslashes( config('laravel-deploy-helper.stages.' . $stage . '.git.http'), '$&');

        SSH::execute($stage, [
            'mkdir ' . $home . '/releases/' . $releaseName,
            'cd ' . $home . '/releases/' . $releaseName,
            'git clone -b ' . $branch . ' ' . $git . ' .',
        ]);
```

Like this it worked

**Comment by RamonSmit** [comment]
Well, going to implant that then! Better something then nothing I guess ;-)

**Comment by rpsimao** [comment]
Yes, its a bit clunky, but it does the job, better to add more symbols, I guess.

**Comment by RamonSmit** [comment]
Yes, Tonight or tomorrow I will look for interfering characters, for now, going to implant this 👍

**Comment by RamonSmit** [comment]
Signed of as v1.0.8 :-) 
Thank you very much for helping! 😄

**Comment by iJos** [comment]
@RamonSmit  The symbol I'm using just near the '@' symbol is the '$'.

So, it is temporarily fixed?

**Comment by RamonSmit** [comment]
Yes correctly, latest release should be working for you ;-)

**Comment by iJos** [comment]
Yes, it is working perfectly now, I've just run two releases without problems!

Thank you! 👍

**Comment by RamonSmit** [comment]
No problem 😄! 

Thank you for using the package! 👍

**Comment by rpsimao** [comment]
@RamonSmit, it turns out,  all it's needed is to put single quotes `" ' ". $url . " ' "` between the url.

Like this:
```
$url = config('laravel-deploy-helper.stages.'.$stage.'.git.http');

SSH::execute($stage, [
           'mkdir '.$home.'/releases/'.$releaseName,
           'cd '.$home.'/releases/'.$releaseName,
           'git clone -b '.$branch.' '. "'". $url . "'" .' .',
       ]);
```

No need to add slashes.
I've made several deployments, successfully.

Sometimes the simple solution is the ONE ;-)

Edit: Deployer.php line 82 typo: direcroty => directory

**Comment by RamonSmit** [comment]
Well, it's a thing to test! Thanks for looking for it tho 👍 
I will test this with multiple passwords later this day 😄 

Edit: re opening, so I cannot forget to test and implement :)

**Comment by RamonSmit** [comment]
Tagged v1.0.10 with this fix, seemd to work fine in my tests :)

**Comment by rpsimao** [comment]
@RamonSmit, sorry for reopen this one, but your package is exactly what I was looking for!!
Just trying to improve it.

Regarding the user:passwd in the URL we can use the ssh url like: 

`"git@github.com:DALTCORE/laravel-deploy-helper.git"`
 
We just have to deploy our computer ssh pub key to the Git server.
I've tested with Github and my own local Gitlab server and it worked, I haven´t tested it with Bitbucked, maybe @iJos could give it a try.

Right now my config file:

```
.....
'production' => [
            'git' => [
                'http' => 'git@gitlab.upgrade.group:rpsimao/stuff.git',
            ],
......
```


If all worked it was only a matter of updating the README file to conteplate the 2 methods (http / ssh) for pulling the code.

**Comment by RamonSmit** [comment]
Seems legit! If @iJos can confirm this works?

Then I will change
```
.....
'production' => [
            'git' => [
                'http' => 'git@gitlab.upgrade.group:rpsimao/stuff.git',
           ]
......
```

to 
```
.....
'production' => [
           'git' => 'git@gitlab.upgrade.group:rpsimao/stuff.git',
......
```
for the config with keeping backwards compatibility :-)

Whats your opinion about it @rpsimao?

**Comment by rpsimao** [comment]
Perfect!
If @iJos cannot confirm I'll create a Bitbucket account and tested it.

**Comment by RamonSmit** [comment]
Thank you! 👍

**Comment by rpsimao** [comment]
@RamonSmit I'm a very impacient guy, so I created a private repo in Bitbucket, deploy the server pub ssh key to my Bitbucket account, and voilá, it worked!
Made several successful deployments

```
......
'production' => [
            'git' => [
                'http' => 'git@bitbucket.org:rpsimao/stuff.git',
            ],
........
```

**Comment by RamonSmit** [comment]
@rpsimoa briljant! 

Will make my changes asap! I think this is a really wanted feature :-) Thanks!

**Comment by RamonSmit** [comment]
@rpsimao released under v1.1.0 :-) Thanks for your input 👍

**Comment by rpsimao** [comment]
Tested the new version. OK here.

Found another typo: Deployer.php Line 58: Migth => Might

**Comment by RamonSmit** [comment]
I see! Changed it, wont publish it yet ;-) but thanks for the heads-up (it's in master at the moment)

**Comment by iJos** [comment]
@RamonSmit Sorry, I was out for business, do you still need any confirmation?

**Comment by RamonSmit** [comment]
@iJos Feedback is always appreciated :)
